### ISSUE TITLE
Typo in method "get_chartheet_names"

### ISSUE THREAD

**Issue by fkrasnov** [jandrew/Spreadsheet-XLSX-Reader-LibXML#102]
Hi, 

It's a small issue. There is a typo in method name **get_chartheet_names**. It is should sounds like **get_chartsheet_names**,  I  suppose.

Regards
  Fedor

**Comment by jandrew** [comment]
Fedor,

Thank you for reporting this issue.   Unfortunately, I am not working on this module any more since it has been [deprecated](https://github.com/jandrew/Spreadsheet-XLSX-Reader-LibXML#deprecation) in favor of the package [Spreadsheet::Reader::ExcelXML](https://metacpan.org/pod/Spreadsheet::Reader::ExcelXML)  ([In github](https://github.com/jandrew/p5-spreadsheet-reader-excelxml)).  The typo in the method name has been fixed there along with other updates and feature additions. I am open to handing off ownership in CPAN/PAUSE to this package to someone who would like to maintain it.  During developement of this package I got stuck on a garbage collection issue that I could never root cause between Moose::XS, libxml2 (C library), and perl core.  I'm not a C programmer and this one was way beyond my expertise.

Best Regards,

Jed
